apiVersion: trafficcontrol.policy.gloo.solo.io/v2
kind: RateLimitClientConfig
metadata:
  name: usage-plans
  namespace: gloo-mesh-addons
spec:
  raw:
    rateLimits:
      - setActions:
          - requestHeaders:
              descriptorKey: usagePlan
              headerName: x-solo-plan
          - requestHeaders:
              descriptorKey: userId
              headerName: x-user-id