apiVersion: trafficcontrol.policy.gloo.solo.io/v2
kind: RateLimitPolicy
metadata:
  name: petstore-rate-limit
  namespace: gloo-mesh-addons
spec:
  applyToRoutes:
    - route:
        labels:
          usagePlans: dev-portal
  config:
    ratelimitServerConfig:
      name: usage-plans
      namespace: gloo-mesh-addons
      cluster:  cluster-1
    ratelimitClientConfig:
      name: usage-plans
      namespace: gloo-mesh-addons
      cluster:  cluster-1
    serverSettings:
      name: rl-server
      namespace: gloo-mesh-addons
    phase:
      postAuthz:
        priority: 3