apiVersion: networking.gloo.solo.io/v2
kind: ExternalService
metadata:
  name: keycloak
  namespace: gloo-mesh-addons
  labels:
    expose: "true"
spec:
  hosts:
    - keycloak
  ports:
    - name: http
      number: 8080
      protocol: HTTP
  selector:
    host: keycloak